Fix psalm issues on new branch
phpspec/phpspec pull request #1439
Opened 2022-12-14 21:09 UTC by ciaranmcnulty

Merges #1438 into the `next` branch, and fixes some extra issues

2022-12-14 21:24 UTC, ciaranmcnulty commented
@rogervila  can you review maybe?

2022-12-15 08:45 UTC, rogervila requested changes

2022-12-15 08:45 UTC, rogervila commented on src/PhpSpec/Console/Application.php
> +     * @return void
the return definition on DocBlock is redundant here

2022-12-15 08:46 UTC, rogervila commented on src/PhpSpec/Console/Application.php
> +     * @return void
A part of that everything looks good @ciaranmcnulty :)

2022-12-15 11:12 UTC, merged